name: publish-with-provenance
on:
  workflow_dispatch:
    inputs:
      npm-latest:
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - name: Setup node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
        with:
          node-version: 20
          check-latest: true
      - name: Bump package versions
        run: |
          sed -i "s/1.0.0/1.1.0/" "package.json"
      - name: Install
        run: |
          npm --version
          npm install
          npm install -g npm@latest
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public 
